---
- hosts: localhost
  become_user: true
  connection: ssh
  gather_facts: true
  tasks:
    - name: install maven
      apt: name=maven state=present
    - name: download file from internet
      get_url: url=https://archive.apache.org/dist/maven/maven-3/3.5.0/binaries/apache-maven-3.5.0-bin.tar.gz dest=/opt
